version: "3.8"

services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - backend_network

  nest-backend:
    container_name: loomi-ecom-api
    image: loomi-ecom-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      LOCAL_HOST: ${LOCAL_HOST}
      DATABASE_URL: ${DATABASE_URL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_SENDER_EMAIL: ${SENDGRID_SENDER_EMAIL}
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - db
    command: >
      sh -c "
        npx prisma generate --schema=src/infra/database/postgres/prisma/schema.prisma &&
        npx prisma migrate deploy --schema=src/infra/database/postgres/prisma/schema.prisma &&
        npm run seed &&
        npm run start
      "

volumes:
  postgres_data: {}

networks:
  backend_network:
    driver: bridge
